version: 2.1
orbs:
  slack: circleci/slack@3.4.2
executors:
  node:
    docker:
      - image: circleci/node:12
commands:
  notify_slack:
    steps:
       - slack/status:
          success_message: 'CI Success'
          failure_message: 'CI Failure'
          webhook: '${SLACK_WEBHOOK}'
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
  test:
    executor: node
    requires:
      - build
    steps:
      - run:
          name: unit test
          command: npm test
      - notify_slack
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
