version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - slack/status:
          success_message: "Success"
          failure_message: "Failure"
          webhook: "${SLACK_WEBHOOK}"
workflows:
  notify-slack:
    jobs:
      - build
